/*
apiVersion: v1
kind: Pod
metadata:
   name: springboot-pod
   labels:
     app: springboot-pod
spec:
   containers:
   - name: springboot-container
     image: lifeofnavin/profiler-springboot-sample
     ports:
     - containerPort: 8080
*/
---

apiVersion: v1
kind: Service
metadata:
    name: loadbalancer-svc
spec:
    type: Loadbalancer
    selector:
        app: hello
    ports:
      - name: http
        protocol: TCP
        port: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: loadbalancer-pod
spec:
    replicas: 2
    selector:
        matchLabels:
            app: hello
    template:
        metadata: 
            labels:
                app: hello
        spec:
            containers:
                - name: springboot-container
                  image: krishnakanthk12/hello:latest
                  imagePullPolicy: Always
